Repository obsproject/obs-deps, pull requests merged in 2022-05, with the labels that each got.

#104 CI: Optimize macOS Qt build
  .github/workflows/main.yml
  CI/macos/build_qt.sh
Labels: enhancement, Seeking Testers

#103 CI: Improve Qt caching
  .github/workflows/main.yml
Labels: enhancement

#101 macos/patches: Cherry-Pick QT macOS text spacing patch
  CI/macos/build_qt.sh
  CI/macos/patches/QTBUG-88495.patch
  README.md
Labels: macOS

#102 macos/patches: Backport QT macOS docking fixes
  CI/macos/build_qt.sh
  CI/macos/patches/QTBUG-70137-1.patch
  CI/macos/patches/QTBUG-70137-2.patch
  CI/macos/patches/QTBUG-70137-3.patch
  README.md
Labels: macOS

#105 FFmpeg: Remove Media Foundation dependency
  .github/workflows/windows_deps.yml
  CI/windows/build_ffmpeg.sh
Labels: bug

#106 Fix broken encrypted SRT connections
  .github/workflows/windows_deps.yml
  CI/windows/build_mbedtls.sh
Labels: bug
